"""some changes

Revision ID: 6811184dd464
Revises: cc1fffd3b47f
Create Date: 2025-11-11 08:36:56.334239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6811184dd464'
down_revision = 'cc1fffd3b47f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('houses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('houses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tittle', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('square', sa.FLOAT(), nullable=False),
    sa.Column('area', sa.FLOAT(), nullable=False),
    sa.Column('price_base', sa.FLOAT(), nullable=False),
    sa.Column('price_with_communications', sa.FLOAT(), nullable=True),
    sa.Column('price_ready', sa.FLOAT(), nullable=True),
    sa.Column('mortgage_price_per_month', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
