"""Changed from float to int

Revision ID: 904a86fa3b23
Revises: ec065da2608c
Create Date: 2025-11-12 20:29:49.200834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904a86fa3b23'
down_revision = 'ec065da2608c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('houses_images')
    with op.batch_alter_table('houses', schema=None) as batch_op:
        batch_op.alter_column('price_base',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('price_with_communications',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('price_ready',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('mortgage_price_per_month',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('houses', schema=None) as batch_op:
        batch_op.alter_column('mortgage_price_per_month',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('price_ready',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('price_with_communications',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('price_base',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    op.create_table('houses_images',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('house_id', sa.INTEGER(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=512), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
