"""Initial migrate

Revision ID: cc1fffd3b47f
Revises: 
Create Date: 2025-11-08 22:14:03.487374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc1fffd3b47f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('houses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tittle', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('square', sa.Float(), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('price_base', sa.Float(), nullable=False),
    sa.Column('price_with_communications', sa.Float(), nullable=True),
    sa.Column('price_ready', sa.Float(), nullable=True),
    sa.Column('mortgage_price_per_month', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('houses')
    # ### end Alembic commands ###
