"""

Revision ID: cef9a6b2cb38
Revises: 904a86fa3b23
Create Date: 2025-11-12 20:33:41.096434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef9a6b2cb38'
down_revision = '904a86fa3b23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('houses', schema=None) as batch_op:
        batch_op.alter_column('area',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('houses', schema=None) as batch_op:
        batch_op.alter_column('area',
               existing_type=sa.String(length=20),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
