"""

Revision ID: ec065da2608c
Revises: 6811184dd464
Create Date: 2025-11-11 14:57:54.627472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec065da2608c'
down_revision = '6811184dd464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('houses_images')
    op.drop_table('houses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('houses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('square', sa.FLOAT(), nullable=False),
    sa.Column('area', sa.FLOAT(), nullable=False),
    sa.Column('price_base', sa.FLOAT(), nullable=False),
    sa.Column('price_with_communications', sa.FLOAT(), nullable=True),
    sa.Column('price_ready', sa.FLOAT(), nullable=True),
    sa.Column('mortgage_price_per_month', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('houses_images',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('house_id', sa.INTEGER(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=512), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
